name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install -G dev

      - name: Remove executable permissions from __init__.py files
        run: |
          find src -name "__init__.py" -exec chmod -x {} +

      - name: Run Lint Ruff
        run: pdm run ruff check src

      - name: Set PYTHONPATH
        run: echo PYTHONPATH=$PYTHONPATH:$(pwd)/src >> $GITHUB_ENV

      - name: Run Pytest
        run: pdm run pytest ./src
